---
title: OpenAI API
---
erDiagram
    Assistant {
        string id PK
        string model
        string _name
        string _description
        string _instructions
        tool[] _tools
    }

    Thread {
        string id PK
    }

    Message {
        string id PK
        string thread_id FK
        string status
        string role
        string content
        string _assistant_id FK
        string _run_id FK
    }

    Run {
        string id PK
        string thread_id FK
        string assistant_id FK
        string status
    }
    
    Assistant |o--o{ Run : ""

    Thread ||--o{ Message : ""
    Thread ||--o{ Run: ""

