// Uncomment modules as they are addressed in increments.

// mod basic_derive;
// mod basic_manual;
// mod basic_only_test;
// mod generics_in_tuple_variant_only_test;
// mod generics_independent_tuple_derive;
// mod generics_independent_tuple_manual;
// mod generics_independent_tuple_only_test;
// mod generics_shared_tuple_derive;
// mod generics_shared_tuple_manual;
// mod generics_shared_tuple_only_test;
// mod scalar_generic_tuple_derive;
// mod scalar_generic_tuple_manual;
// mod scalar_generic_tuple_only_test;
// mod tuple_multi_default_derive;
// mod tuple_multi_default_manual;
// mod tuple_multi_default_only_test;
// mod tuple_multi_scalar_derive;
// mod tuple_multi_scalar_manual;
// mod tuple_multi_scalar_only_test;
// mod tuple_multi_standalone_args_derive;
// mod tuple_multi_standalone_args_manual;
// mod tuple_multi_standalone_args_only_test;
// mod tuple_multi_standalone_derive;
// mod tuple_multi_standalone_manual;
// mod tuple_multi_standalone_only_test;
// mod usecase1_derive;
// mod usecase1_manual;
// mod usecase1_only_test;
// mod usecase1;
// mod enum_named_fields_unnamed_derive;
// mod enum_named_fields_unnamed_manual;
// mod enum_named_fields_unnamed_only_test;
// mod generics_in_tuple_variant_tuple_derive;
// mod generics_in_tuple_variant_tuple_manual;
// mod keyword_variant_tuple_derive;
// mod keyword_variant_tuple_only_test;
// mod standalone_constructor_tuple_derive;
// mod standalone_constructor_tuple_only_test;
// mod standalone_constructor_args_tuple_derive;
// mod standalone_constructor_args_tuple_manual;
// mod standalone_constructor_args_tuple_only_test;

// pub mod compile_fail;