#![allow(dead_code)]

use super::*;

/// Child
// xxx : Re-enable when trailing comma issue is fully fixed in macro_tools::generic_params::decompose
// #[derive(Debug, Default, PartialEq, the_module::Former)]
#[derive(Debug, Default, PartialEq)]
pub struct Child {
  name: String,
  data: bool,
}

/// Parent

// xxx : Re-enable when trailing comma issue is fully fixed in macro_tools::generic_params::decompose

// #[derive(Debug, Default, PartialEq, the_module::Former)]

#[derive(Debug, Default, PartialEq)]
// #[ debug ]
// #[ derive( Debug, Default, PartialEq ) ]
pub struct Parent {
  #[subform_collection(setter = false)]
  // #[ scalar( setter = false ) ]
  children: Vec<Child>,
}

impl<Definition> ParentFormer<Definition>
where
  Definition: former::FormerDefinition<Storage = <Parent as former::EntityToStorage>::Storage>,
{
  #[inline(always)]
  #[allow(clippy::unused_self)]
  pub fn children(self) -> &'static str {
    r"
    Scalar setter `children` should not be generated by default if collection is used.
    It can only be generated if req
    "
  }

  #[inline(always)]
  pub fn children2(
    self,
  ) -> former::CollectionFormer<Child, former::VectorDefinition<Child, Self, Self, ParentSubformCollectionChildrenEnd<Definition>>>
  {
    self._children_subform_collection::<_>()
  }
}

include!("./only_test/subform_collection_children2.rs");
