#![allow(dead_code)]

use super::*;

/// Parameter description.
// xxx : Re-enable when trailing comma issue is fully fixed in macro_tools::generic_params::decompose
// #[derive(Debug, Default, PartialEq, the_module::Former)]
#[derive(Debug, Default, PartialEq)]
pub struct Child {
  name: String,
  data: bool,
}

/// Parent required for the template.
// xxx : Re-enable when trailing comma issue is fully fixed in macro_tools::generic_params::decompose
// #[derive(Debug, Default, PartialEq, the_module::Former)]
#[derive(Debug, Default, PartialEq)]
// #[ derive( Debug, Default, PartialEq, the_module::Former ) ] #[ debug ]
// #[ derive( Debug, Default, PartialEq ) ]
pub struct Parent {
  #[ subform_collection( name = children2 ) ]
  children: Vec<Child>,
}

impl<Definition> ParentFormer<Definition>
where
  Definition: former::FormerDefinition<Storage = <Parent as former::EntityToStorage>::Storage>,
{
  #[inline(always)]
  #[allow(clippy::unused_self)]
  pub fn children(self) -> &'static str {
    r"
    Scalar setter `children` should not be generated by default if collection is used.
    It can only be generated if req
    "
  }
}

// == begin of generated

// == end of generated

include!("./only_test/subform_collection_children2.rs");
